name: sheet-music-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: sdcc-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: lilypond
        shell: cmd
        run: |
          curl https://gitlab.com/lilypond/lilypond/-/releases/v2.24.4/downloads/lilypond-2.24.4-mingw-x86_64.zip --output setup.zip &&^ 
          7z x setup.zip &&^
          cd lilypond-2.24.4 &&^
          dir

      - shell: cmd
        run: |
          SET PATH=%PATH%;^
          lilypond-2.24.4\bin
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

